import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Navbar />
          <main className="bg-[#030F26] w-[100%] flex flex-col justify-start items-center min-h-[100vh] font-erode">
            {children}
          </main>
          <div className="h-[92px] w-full bg-[#030F26]"></div>
          <Footer />
          <div className="h-[92px] w-full bg-[#030F26]"></div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
